all1:
	g++-5 -O3 -Wall -Itrng-4.19 -Ltrng-4.19/src/.libs HLM_KMP_Flux_temperature_Test1_Hwang.cpp -o exe_flux3_1 -std=c++17 -ltrng4 -fopenmp

all2:
	g++-5 -O3 -Wall -Itrng-4.19 -Ltrng-4.19/src/.libs HLM_KMP_Flux_temperature_Test2_Hwang.cpp -o exe_flux3_2 -std=c++17 -ltrng4 -fopenmp

run1:
	./exe_flux3_1

run2:
	./exe_flux3_2
